{{- if .Values.authentication.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: jolokia-auth
  labels:
    {{- include "sts-cassandra-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  password: TTBucDQ1NXcwcmQ=
  username: am9sb2tpYS11c2Vy
{{- end }}