apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "casskop.fullname" . }}
  labels:
    app: {{ template "casskop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: cassandra
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "casskop.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "casskop.name" . }}
        app: {{ template "casskop.name" . }}
        operator: cassandra
        release: {{ .Release.Name }}
    spec:
{{- if .Values.image.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets.name }}
{{- end }}
{{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "casskop.name" . }}
{{- end }}
      securityContext:
        runAsUser: 1000
{{- if .Values.debug.enabled }}
      shareProcessNamespace: true
{{- end }}
      containers:
      - name: {{ template "casskop.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
        - casskop
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: {{ .Values.livenessProbe.timeouts.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.timeouts.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.timeouts.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: {{ .Values.readinessProbe.timeouts.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.timeouts.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.timeouts.failureThreshold }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "casskop"
{{- if .Values.debug.enabled }}
          - name: LOG_LEVEL
            value: Debug
{{- end }}
