redis:
  enabled: true
  architecture: replication
  fullnameOverride: redis-sentinel
  auth:
    enabled: true
    sentinel: true
    existingSecret: "redis-auth"
  sentinel:
    enabled: true

# redis-sentinel:
#   enabled: true
#   architecture: replication
#   fullnameOverride: redis-sentinel
